// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the bound service instance.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credstore$0 from "../credstore/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * About returns identity and diagnostic info.
 */
export function About(): $CancellablePromise<$models.AboutDTO> {
    return $Call.ByID(1436006898).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BeginPair makes first contact with a device port and returns the certificate
 * fingerprint it presents (uppercase colon-hex), for the user to compare against
 * the Web pairing page. No trust is established until ConfirmPair is called.
 */
export function BeginPair(serverURL: string): $CancellablePromise<string> {
    return $Call.ByID(3105165426, serverURL);
}

/**
 * Boot loads credentials and, if already paired, starts the sync runtime.
 */
export function Boot(store: credstore$0.Store | null): $CancellablePromise<void> {
    return $Call.ByID(3935694721, store);
}

/**
 * HandleNotificationResponse routes a notification button tap back to the engine:
 * confirm sends/pulls the held item, anything else discards it. data carries the
 * item's kind ("upload"|"download") and id.
 */
export function HandleNotificationResponse(action: string, data: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(3512762007, action, data);
}

/**
 * Language returns the stored UI language for the tray menu ("zh" | "en"),
 * defaulting to Chinese.
 */
export function Language(): $CancellablePromise<string> {
    return $Call.ByID(611185343);
}

/**
 * LoadWindowBounds returns the saved settings-window bounds. ok is false when none
 * were saved (first launch), so the caller centers the window instead.
 */
export function LoadWindowBounds(): $CancellablePromise<[number, number, number, number, boolean]> {
    return $Call.ByID(3199769152);
}

/**
 * Pair runs the pairing flow and, on success, starts the runtime. The server
 * fingerprint must have been confirmed by the user against the Web pairing page.
 */
export function Pair(serverURL: string, fingerprint: string, code: string, deviceName: string): $CancellablePromise<void> {
    return $Call.ByID(396142325, serverURL, fingerprint, code, deviceName);
}

/**
 * Peers 拉取同用户全部设备及其公钥指纹，并结合本机 TOFU 缓存标注信任状态，
 * 供「关于」页做跨设备人工互验（prd/03 §5.3）。
 */
export function Peers(): $CancellablePromise<$models.PeerDTO[]> {
    return $Call.ByID(1371751386).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * PersistWindowBounds writes the last in-memory window bounds to the local profile.
 */
export function PersistWindowBounds(): $CancellablePromise<void> {
    return $Call.ByID(1992188330);
}

/**
 * PickReceivedDir opens a native directory picker and, if the user chose a folder,
 * applies it as the received-files directory. Returns the chosen path (empty when
 * the user cancelled).
 */
export function PickReceivedDir(): $CancellablePromise<string> {
    return $Call.ByID(618606942);
}

/**
 * RecentHistory returns the current session's sync history (newest last).
 */
export function RecentHistory(): $CancellablePromise<$models.HistoryDTO[]> {
    return $Call.ByID(4031581202).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetAutoDownloadSize sets the device's auto-download threshold (inherit or override).
 */
export function SetAutoDownloadSize(inherit: boolean, bytes: number): $CancellablePromise<void> {
    return $Call.ByID(3095052941, inherit, bytes);
}

/**
 * SetAutoUploadSize sets the device's auto-upload threshold (inherit or override).
 */
export function SetAutoUploadSize(inherit: boolean, bytes: number): $CancellablePromise<void> {
    return $Call.ByID(3815108260, inherit, bytes);
}

/**
 * SetAutostart enables or disables launch-at-login (OS-level) and persists the
 * desired state to the local profile.
 */
export function SetAutostart(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(4112236608, enable);
}

/**
 * SetDirection sets the sync direction (bidirectional | upload_only |
 * download_only), applies it to the running engine and persists it.
 */
export function SetDirection(direction: string): $CancellablePromise<void> {
    return $Call.ByID(546603992, direction);
}

/**
 * SetFileRetention sets the received-files retention: inherit the account default
 * or override it locally with days (1..365). Persisted and applied immediately.
 */
export function SetFileRetention(inherit: boolean, days: number): $CancellablePromise<void> {
    return $Call.ByID(2497098173, inherit, days);
}

/**
 * SetLanguage records the resolved UI language (pushed by the settings window),
 * persists it to the profile, and rebuilds the tray menu so it follows the
 * language switch. The frontend i18n provider calls this on load and on change.
 */
export function SetLanguage(lang: string): $CancellablePromise<void> {
    return $Call.ByID(948757889, lang);
}

/**
 * SetMaxSyncSize sets the device's max sync size: inherit the account default or
 * override locally with a positive byte count. Content above it is dropped.
 */
export function SetMaxSyncSize(inherit: boolean, bytes: number): $CancellablePromise<void> {
    return $Call.ByID(2956167905, inherit, bytes);
}

/**
 * SetNotifyPolicy sets the notification verbosity (quiet | default | verbose).
 */
export function SetNotifyPolicy(policy: string): $CancellablePromise<void> {
    return $Call.ByID(117423772, policy);
}

/**
 * SetPaused toggles syncing and persists it to the local profile. Pausing stops
 * both upload (clipboard monitor) and download (pending pulls); resuming pulls any
 * deliveries that queued while paused.
 */
export function SetPaused(paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(3736125889, paused);
}

/**
 * SetSyncTypes sets the device's allowed content types: inherit the account default
 * or override with a local set (must be non-empty when overriding).
 */
export function SetSyncTypes(inherit: boolean, types: string[]): $CancellablePromise<void> {
    return $Call.ByID(4016958937, inherit, types);
}

/**
 * SetTempDir changes the received-files directory (local-only) and persists it.
 * An empty dir restores the default. Existing files are not migrated; the new
 * store is used for subsequent receives and cleanup.
 */
export function SetTempDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2960864280, dir);
}

/**
 * SetWindowBounds records the settings window's position/size in memory (cheap,
 * called on every move/resize). Call PersistWindowBounds to flush it to disk.
 */
export function SetWindowBounds(x: number, y: number, w: number, h: number): $CancellablePromise<void> {
    return $Call.ByID(3460230138, x, y, w, h);
}

/**
 * SetWindowsBackdrop 设置 Windows 11 的窗口材质（mica | acrylic）并持久化；
 * 通过宿主回调重建窗口即时生效（Windows 10 仍回退普通窗口）。
 */
export function SetWindowsBackdrop(kind: string): $CancellablePromise<void> {
    return $Call.ByID(643823030, kind);
}

/**
 * Status returns the current overview state.
 */
export function Status(): $CancellablePromise<$models.StatusDTO> {
    return $Call.ByID(876698891).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SuggestedDeviceName returns the local machine name to pre-fill the pairing form.
 */
export function SuggestedDeviceName(): $CancellablePromise<string> {
    return $Call.ByID(4046844961);
}

/**
 * TestNotification sends a system-level test notification, returning an error so
 * the UI can explain why nothing appeared (e.g. permission denied / unsupported).
 */
export function TestNotification(): $CancellablePromise<void> {
    return $Call.ByID(2859447562);
}

/**
 * TrustPeer 在用户跨设备重新互验后，信任某台对端设备的新公钥指纹并恢复同步。
 */
export function TrustPeer(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(490410061, deviceID);
}

/**
 * TrustServerFingerprint 在用户与 Web 后台核对一致后，显式信任服务器当前出示
 * 的新证书指纹：写入凭据目录并重启同步运行时使新 pin 生效。绝不自动调用。
 */
export function TrustServerFingerprint(): $CancellablePromise<void> {
    return $Call.ByID(238105534);
}

/**
 * Unpair stops the runtime and erases credentials (destructive reset).
 */
export function Unpair(): $CancellablePromise<void> {
    return $Call.ByID(3644957598);
}

/**
 * WindowsBackdrop 返回持久化的 Windows 窗口材质偏好（"mica" | "acrylic"），
 * 供宿主(main.go)创建窗口时读取。
 */
export function WindowsBackdrop(): $CancellablePromise<string> {
    return $Call.ByID(4075577972);
}

// Private type creation functions
const $$createType0 = $models.AboutDTO.createFrom;
const $$createType1 = $models.PeerDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.HistoryDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.StatusDTO.createFrom;
