// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AboutDTO is the identity/diagnostics state shown on the About tab.
 */
export class AboutDTO {
    "device_id": string;
    "user_id": string;
    "server_id": string;
    "key_fingerprint": string;
    "version": string;

    /** Creates a new AboutDTO instance. */
    constructor($$source: Partial<AboutDTO> = {}) {
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("server_id" in $$source)) {
            this["server_id"] = "";
        }
        if (!("key_fingerprint" in $$source)) {
            this["key_fingerprint"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AboutDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AboutDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AboutDTO($$parsedSource as Partial<AboutDTO>);
    }
}

/**
 * HistoryDTO is one session sync-history row for the UI.
 */
export class HistoryDTO {
    "at": string;
    "direction": string;
    "content_type": string;
    "size_bytes": number;
    "ok": boolean;

    /**
     * "ok" | "ignored" | "failed"
     */
    "status": string;
    "detail": string;
    "summary": string;

    /** Creates a new HistoryDTO instance. */
    constructor($$source: Partial<HistoryDTO> = {}) {
        if (!("at" in $$source)) {
            this["at"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("content_type" in $$source)) {
            this["content_type"] = "";
        }
        if (!("size_bytes" in $$source)) {
            this["size_bytes"] = 0;
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryDTO($$parsedSource as Partial<HistoryDTO>);
    }
}

/**
 * PeerDTO 是「关于」页公钥互验列表中的一台设备。
 */
export class PeerDTO {
    "device_id": string;
    "name": string;
    "platform": string;
    "status": string;
    "online": boolean;
    "self": boolean;
    "key_fingerprint": string;

    /**
     * TrustState: self | trusted | mismatch | unseen（本机尚未与其同步过）
     */
    "trust_state": string;

    /** Creates a new PeerDTO instance. */
    constructor($$source: Partial<PeerDTO> = {}) {
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("self" in $$source)) {
            this["self"] = false;
        }
        if (!("key_fingerprint" in $$source)) {
            this["key_fingerprint"] = "";
        }
        if (!("trust_state" in $$source)) {
            this["trust_state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PeerDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeerDTO($$parsedSource as Partial<PeerDTO>);
    }
}

/**
 * PeerMismatchDTO 是一台公钥指纹失配、同步被阻断的对端设备（持续告警用）。
 */
export class PeerMismatchDTO {
    "device_id": string;
    "device_name": string;

    /**
     * 本机曾信任的指纹
     */
    "trusted_fingerprint": string;

    /**
     * 服务端当前下发的指纹
     */
    "new_fingerprint": string;

    /** Creates a new PeerMismatchDTO instance. */
    constructor($$source: Partial<PeerMismatchDTO> = {}) {
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("device_name" in $$source)) {
            this["device_name"] = "";
        }
        if (!("trusted_fingerprint" in $$source)) {
            this["trusted_fingerprint"] = "";
        }
        if (!("new_fingerprint" in $$source)) {
            this["new_fingerprint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerMismatchDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PeerMismatchDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeerMismatchDTO($$parsedSource as Partial<PeerMismatchDTO>);
    }
}

/**
 * SizeSettingDTO is a per-field inherit/override size policy for the UI: when
 * Inherit is true the device uses the account default (shown as InheritedBytes);
 * otherwise OverrideBytes applies locally.
 */
export class SizeSettingDTO {
    "inherit": boolean;

    /**
     * local override (0 when inheriting)
     */
    "override_bytes": number;

    /**
     * resolved account default (for placeholder)
     */
    "inherited_bytes": number;

    /** Creates a new SizeSettingDTO instance. */
    constructor($$source: Partial<SizeSettingDTO> = {}) {
        if (!("inherit" in $$source)) {
            this["inherit"] = false;
        }
        if (!("override_bytes" in $$source)) {
            this["override_bytes"] = 0;
        }
        if (!("inherited_bytes" in $$source)) {
            this["inherited_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SizeSettingDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SizeSettingDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SizeSettingDTO($$parsedSource as Partial<SizeSettingDTO>);
    }
}

/**
 * StatusDTO is the overview state shown by the frontend.
 */
export class StatusDTO {
    "paired": boolean;
    "connected": boolean;
    "paused": boolean;
    "direction": string;
    "notify_policy": string;
    "server_url": string;

    /**
     * 实例显示名（来自服务端实例设置，随配置刷新）
     */
    "server_name": string;
    "server_fingerprint": string;

    /**
     * ServerFPMismatch 表示服务器证书指纹与已固定值不一致、连接已被阻断，
     * 需要用户核对后显式处理（信任新指纹或重新配对），绝不静默接受。
     */
    "server_fp_mismatch": boolean;

    /**
     * 服务器当前出示的证书指纹
     */
    "new_server_fingerprint": string;

    /**
     * PeerMismatches 是公钥指纹失配被阻断的对端设备列表（界面持续告警）。
     */
    "peer_mismatches": PeerMismatchDTO[];
    "sync_count": number;

    /**
     * successful uploads this session
     */
    "upload_count": number;

    /**
     * successful downloads this session
     */
    "download_count": number;
    "last_error": string;
    "permission_warning": string;

    /**
     * local override (empty = default)
     */
    "temp_dir": string;

    /**
     * resolved received-files directory
     */
    "received_dir": string;

    /**
     * inherit the account default
     */
    "file_ttl_inherit": boolean;

    /**
     * local override (0 when inheriting)
     */
    "file_ttl_days": number;

    /**
     * account default from effective config
     */
    "inherited_file_ttl_days": number;

    /**
     * launch at login
     */
    "autostart": boolean;

    /**
     * "darwin" | "windows" (drives platform-specific UI)
     */
    "platform": string;

    /**
     * Windows 11 窗口材质:mica | acrylic
     */
    "windows_backdrop": string;

    /**
     * 客户端自动更新检查：发现更新时置位，前端在顶栏展示「新版本」入口。
     * 是否存在更新的正式版
     */
    "update_available": boolean;

    /**
     * 最新正式版标签（如 v1.2.0）
     */
    "latest_version": string;

    /**
     * 对应版本的 release 页面地址
     */
    "update_url": string;

    /**
     * Sync policy: per-field inherit/override (device settings) resolved against
     * the account default. Populated once connected; zero values until then.
     */
    "max_sync_size": SizeSettingDTO;
    "auto_upload": SizeSettingDTO;
    "auto_download": SizeSettingDTO;
    "sync_types": TypesSettingDTO;

    /** Creates a new StatusDTO instance. */
    constructor($$source: Partial<StatusDTO> = {}) {
        if (!("paired" in $$source)) {
            this["paired"] = false;
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("notify_policy" in $$source)) {
            this["notify_policy"] = "";
        }
        if (!("server_url" in $$source)) {
            this["server_url"] = "";
        }
        if (!("server_name" in $$source)) {
            this["server_name"] = "";
        }
        if (!("server_fingerprint" in $$source)) {
            this["server_fingerprint"] = "";
        }
        if (!("server_fp_mismatch" in $$source)) {
            this["server_fp_mismatch"] = false;
        }
        if (!("new_server_fingerprint" in $$source)) {
            this["new_server_fingerprint"] = "";
        }
        if (!("peer_mismatches" in $$source)) {
            this["peer_mismatches"] = [];
        }
        if (!("sync_count" in $$source)) {
            this["sync_count"] = 0;
        }
        if (!("upload_count" in $$source)) {
            this["upload_count"] = 0;
        }
        if (!("download_count" in $$source)) {
            this["download_count"] = 0;
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }
        if (!("permission_warning" in $$source)) {
            this["permission_warning"] = "";
        }
        if (!("temp_dir" in $$source)) {
            this["temp_dir"] = "";
        }
        if (!("received_dir" in $$source)) {
            this["received_dir"] = "";
        }
        if (!("file_ttl_inherit" in $$source)) {
            this["file_ttl_inherit"] = false;
        }
        if (!("file_ttl_days" in $$source)) {
            this["file_ttl_days"] = 0;
        }
        if (!("inherited_file_ttl_days" in $$source)) {
            this["inherited_file_ttl_days"] = 0;
        }
        if (!("autostart" in $$source)) {
            this["autostart"] = false;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("windows_backdrop" in $$source)) {
            this["windows_backdrop"] = "";
        }
        if (!("update_available" in $$source)) {
            this["update_available"] = false;
        }
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("update_url" in $$source)) {
            this["update_url"] = "";
        }
        if (!("max_sync_size" in $$source)) {
            this["max_sync_size"] = (new SizeSettingDTO());
        }
        if (!("auto_upload" in $$source)) {
            this["auto_upload"] = (new SizeSettingDTO());
        }
        if (!("auto_download" in $$source)) {
            this["auto_download"] = (new SizeSettingDTO());
        }
        if (!("sync_types" in $$source)) {
            this["sync_types"] = (new TypesSettingDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusDTO {
        const $$createField10_0 = $$createType1;
        const $$createField27_0 = $$createType2;
        const $$createField28_0 = $$createType2;
        const $$createField29_0 = $$createType2;
        const $$createField30_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("peer_mismatches" in $$parsedSource) {
            $$parsedSource["peer_mismatches"] = $$createField10_0($$parsedSource["peer_mismatches"]);
        }
        if ("max_sync_size" in $$parsedSource) {
            $$parsedSource["max_sync_size"] = $$createField27_0($$parsedSource["max_sync_size"]);
        }
        if ("auto_upload" in $$parsedSource) {
            $$parsedSource["auto_upload"] = $$createField28_0($$parsedSource["auto_upload"]);
        }
        if ("auto_download" in $$parsedSource) {
            $$parsedSource["auto_download"] = $$createField29_0($$parsedSource["auto_download"]);
        }
        if ("sync_types" in $$parsedSource) {
            $$parsedSource["sync_types"] = $$createField30_0($$parsedSource["sync_types"]);
        }
        return new StatusDTO($$parsedSource as Partial<StatusDTO>);
    }
}

/**
 * TypesSettingDTO is the inherit/override allowed-content-types policy for the UI.
 */
export class TypesSettingDTO {
    "inherit": boolean;

    /**
     * local override (nil when inheriting)
     */
    "override": string[];

    /**
     * resolved account default
     */
    "inherited": string[];

    /** Creates a new TypesSettingDTO instance. */
    constructor($$source: Partial<TypesSettingDTO> = {}) {
        if (!("inherit" in $$source)) {
            this["inherit"] = false;
        }
        if (!("override" in $$source)) {
            this["override"] = [];
        }
        if (!("inherited" in $$source)) {
            this["inherited"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypesSettingDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TypesSettingDTO {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("override" in $$parsedSource) {
            $$parsedSource["override"] = $$createField1_0($$parsedSource["override"]);
        }
        if ("inherited" in $$parsedSource) {
            $$parsedSource["inherited"] = $$createField2_0($$parsedSource["inherited"]);
        }
        return new TypesSettingDTO($$parsedSource as Partial<TypesSettingDTO>);
    }
}

// Private type creation functions
const $$createType0 = PeerMismatchDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = SizeSettingDTO.createFrom;
const $$createType3 = TypesSettingDTO.createFrom;
const $$createType4 = $Create.Array($Create.Any);
