// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Store is a handle to a device configuration directory.
 */
export class Store {

    /** Creates a new Store instance. */
    constructor($$source: Partial<Store> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Store instance from a string or object.
     */
    static createFrom($$source: any = {}): Store {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Store($$parsedSource as Partial<Store>);
    }
}
